### ISSUE TITLE
Кнопка не ровно стоит 

### ISSUE THREAD

**Issue by a-berezhkov** [Zhazgul21/Dodo#3]
https://github.com/Zhazgul21/Dodo/blob/d6bd80008298b558ee4f105da7382650314a9fdb/index.html#L169

<img width="339" alt="image" src="https://user-images.githubusercontent.com/90522407/225022315-79af1ffc-8bc4-46bb-9c51-9011a18329cd.png">

**Comment by Zhazgul21** [comment]
fixed
